<?xml version="1.0"?>
<package format="2">
  <name>sbd_vic</name>
  <version>0.0.1</version>
  <description>Scripts/orchestrators for SbD-VIC</description>
  <maintainer email="sophia@todo.todo">sophia</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>actionlib_msgs</exec_depend>
  <exec_depend>fr3_controllers</exec_depend>
  <exec_depend>franka_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>roscpp</exec_depend>
</package>
